version: "3"
services:
  db:
    image: postgres:12.20-alpine3.20
    env_file:
      - postgre-variables.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql